const cars=[
{name:"Mercedes-Benz GLE 450",year:"2024",km:"32,000 KM",fuel:"Petrol",price:"US$89,500",img:"https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=85"},
{name:"Range Rover Sport",year:"2023",km:"18,400 KM",fuel:"Petrol",price:"US$118,000",img:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=85"},
{name:"BMW X5 xDrive40i",year:"2024",km:"21,700 KM",fuel:"Petrol",price:"US$92,000",img:"https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=1400&q=85"},
{name:"Toyota Land Cruiser",year:"2023",km:"27,900 KM",fuel:"Diesel",price:"US$96,500",img:"https://images.unsplash.com/photo-1621007750207-8e4d1c4f1a7b?auto=format&fit=crop&w=1400&q=85"},
{name:"Mercedes-Benz C-Class",year:"2024",km:"14,200 KM",fuel:"Petrol",price:"US$64,500",img:"https://images.unsplash.com/photo-1617531653332-bd46c24f2068?auto=format&fit=crop&w=1400&q=85"},
{name:"Ford Ranger Wildtrak",year:"2024",km:"19,800 KM",fuel:"Diesel",price:"US$58,500",img:"https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?auto=format&fit=crop&w=1400&q=85"}];
export default function Home(){return <main><nav className="nav"><div className="container navInner"><div className="brand">PREMIUM AUTO <span>ZIMBABWE</span></div><div className="links"><a href="#stock">Stock</a><a href="#experience">Experience</a><a href="#sourcing">Sourcing</a><a href="#contact">Contact</a></div><a className="navCta" href="#stock">View Collection</a></div></nav>
<section className="hero"><div className="heroImage"/><div className="container heroContent"><div className="eyebrow">Harare · Zimbabwe · Curated Automotive</div><h1>Drive<br/>Different.</h1><p>A new standard for premium vehicle discovery. Exceptional cars, beautifully presented and ready for your next chapter.</p><div className="buttons"><a className="btn btnLight" href="#stock">Explore Collection</a><a className="btn btnGhost" href="#contact">Speak to Sales</a></div></div><div className="heroMeta"><div className="container heroMetaInner"><div className="slideCount"><b>01</b> / 04</div><div className="heroNote">Curated premium selection</div></div></div></section>
<section className="section" id="stock"><div className="container"><div className="sectionHead"><div><div className="kicker">The collection</div><h2>Selected.<br/>Not crowded.</h2></div><p className="sectionIntro">A considered collection of premium SUVs, executive sedans and capable 4x4s. Every listing is presented with the details serious buyers need.</p></div><div className="filters"><div className="filter">All Vehicles</div><div className="filter">SUV</div><div className="filter">Luxury</div><div className="filter">4x4</div><div className="filter">Under US$60k</div></div><div className="grid">{cars.map(c=><article className="car" key={c.name}><div className="carImg" style={{backgroundImage:`url('${c.img}')`}}/><div className="carBody"><div className="carTop"><h3>{c.name}</h3><div className="price">{c.price}</div></div><div className="spec"><span>{c.year}</span><span>{c.km}</span><span>{c.fuel}</span></div><a className="view" href="#contact">View vehicle →</a></div></article>)}</div></div></section>
<section className="manifesto" id="experience"><div className="container"><div className="kicker">The experience</div><h2>Luxury should feel effortless.</h2><p>From the first image to the first conversation, every touchpoint is designed around clarity, confidence and a faster path to the right vehicle.</p><div className="featureGrid"><div className="feature"><small>01 / SEARCH</small><strong>Find your next car without the noise.</strong></div><div className="feature"><small>02 / WHATSAPP</small><strong>Talk directly to a sales specialist.</strong></div><div className="feature"><small>03 / SOURCE</small><strong>Can't find it? We'll source it.</strong></div><div className="feature"><small>04 / VIEW</small><strong>Book a private viewing in Harare.</strong></div></div></div></section>
<section className="section finder" id="sourcing"><div className="container"><div className="kicker">Find your match</div><h2>Tell us what<br/>you're looking for.</h2><div className="finderBox"><div className="field"><label>Budget</label><div>US$20k — US$150k+</div></div><div className="field"><label>Body type</label><div>SUV / Sedan / 4x4</div></div><div className="field"><label>Make</label><div>Any make</div></div><a className="finderBtn" href="#contact">Show my matches →</a></div></div></section>
<footer className="footer" id="contact"><div className="container footerGrid"><div><div className="brand">PREMIUM AUTO ZIMBABWE</div><p>A cinematic digital showroom concept built for Zimbabwe's premium automotive market. Replace the demo identity, stock and contact details for each dealership.</p></div><div className="footerLinks"><a href="#stock">Stock</a><a href="#sourcing">Source a Car</a><a href="#contact">WhatsApp Sales</a></div></div></footer></main>}